controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\RegisterAction::index
routing:
  resource: "../src/Projects/List/Infrastructure/Config/routes.yaml"
  type: yaml

tasks_list_routes:
  resource: '../src/Tasks/List/Infrastructure/Config/routes.yaml'
  type: yaml